### ISSUE TITLE
review the WIS Guide Part V and send feedback before July 9

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#119]
As per https://github.com/wmo-im/wcmp/wiki/Meeting-2021-07-02#actions, we need to review the document on WMO infrastructure as prepared by @amilan17 given our updates as per #92 .  We should all have been sent a link to the document (please let @amilan17 know if not).

@wmo-im/tt-wismd please note input/feedback is due by **Friday 09 July 2021**

(manually cc'ing @solson-nws until he is added to @wmo-im/tt-wismd and @wmo-im/et-metadata)

**Comment by jsieland** [comment]
Just had a read through and added some comments in the document @amilan17 sent - but will also add them here for completeness:

- section 5.7.11 mentions the WCMP1.3_MAND-Template.xml file but all other mentions have been removed
- in chapter 5.8 in some of the tables the names of the template values are not seperated by hyphens, e.g. `ADDMETADATACONTACTORGANISATIONNAME` instead of `ADD-METADATA-CONTACT-ORGANISATION-NAME` 

Beside that I'm fine with the result - thanks @amilan17 !

**Comment by Amienshxq** [comment]
@tomkralidis hello tom, I have just read Chapter 5, I found that some of the following links in 5.1.3  and 5.6.1 did not open : http://wis.wmo.int/MD-Templates,  http://wis.wmo.int/MD_Index, http://wis.wmo.int/WIScentresDb, https://wiswiki.wmo.int/tiki-index.php?page=ManualWIS
And There is a conflict in the definition of the time format between 5.8.1.5 and 5.8.2.2 ( or 5.8.2.3),  Is it necessary to add the letter “Z” at the end of time when the time format includes hours and minutes?

The rest of the chapter 5 is good for me , thanks  @amilan17 ~

**Comment by tomkralidis** [comment]
Thanks for the comments @Amienshxq / @jsieland.  @amilan17 no further comments on my side.  Let us know if there are other questions/issues.  Thanks for pushing this through!

**Comment by tomkralidis** [comment]
Feedback provided.
