### ISSUE TITLE
Define the KPI E Temporal information

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#21]

**Comment by efucile** [comment]
working on this branch https://github.com/wmo-im/wmcp/blob/KPI-E/KPI/E.adoc

**Comment by efucile** [comment]
check
1. presence of the time information.
1. update the guidance 

Proposal by Kate
extent to be now-now . At the moment for observations the time extent is wrong because it is a date in the past and now. This is not true because the only accessible data are from the 24h cache.

**Comment by efucile** [comment]
The proposal from Kate not yet approved. More discussion needed.

**Comment by efucile** [comment]
Proposal from Guillaume is to do now+24h

**Comment by kateroberts** [comment]
Team to further discuss ideal tempExtent for bulletins, and compare with Guidance at
https://www.wmo.int/pages/prog/www/WIS/documents/Guide-to-WIS-en.pdf [old url] and [?]

**Comment by kateroberts** [comment]
new url for WMCP Guidance: https://library.wmo.int/doc_num.php?explnum_id=4004

**Comment by kateroberts** [comment]
Relevant WIS WMCP Guide page numbers are: pg 41-42
 [WMCP Guidance: https://library.wmo.int/doc_num.php?explnum_id=4004 ]

The key issue is that people currently searching for older data (say 2017 data), when using a WIS catalogue, or even the GEOSS catalogue, etc, will (inappropriately) find WIS BULLETIN metadata records in their search results.  
And they might even make the effort of registering with a GISC, for access to the advertised data ... only to find out that the data doesn't cover 2017. This would be/is, a very negative user experience.

The proposed solution is aiming, within what is possible in the metadata standard, to indicate the correct temporal coverage of the available data (which, for a WMO Bulletin, is typically latest 24 hours).
The use of the term "now" is off-putting.   However, as indicated in the Guide, it can be qualified using 'description'.
For instance:
![image](https://user-images.githubusercontent.com/8108122/70714689-c47d2300-1d3c-11ea-9ffc-360824706125.png)
or
![image](https://user-images.githubusercontent.com/8108122/70714896-37869980-1d3d-11ea-9314-40204c36d82d.png)

(In case the images don't work,, this is an example of a record for a forecast): http://www.bom.gov.au/metadata/catalogue/19115/ANZCW0503900324)

**Comment by gaubert** [comment]
I have written the first version of the Temporal extent KPI. Please check

**Comment by gaubert** [comment]
For the issue regarding the bulletin time period we have to discuss.

![image](https://user-images.githubusercontent.com/1482/101181444-2d942f80-364d-11eb-97ab-e01ef6e4be13.png)

A begin, end time is needed and a description can be added. The begin/end time is mandatory and description is optional.
What should begin or end contain because only 24 hr is retained in the cache. It cannot be a relative duration (begin and end have to contain real dates).

Something like that could be recommended:

```
<gmd:extent>
   <gmd:EX_Extent>
     <gmd:temporalElement>
       <gmd:EX_TemporalExtent>
          <gmd:extent>
             <gml:description>Last 24hrs available</gml:description>
             <gml:TimePeriod gml:id="extent">
                 <gml:beginPosition>1977-03-10T11:45:30</gml:beginPosition>
                 <gml:endPosition>2005-01-15T09:10:00</gml:endPosition>
             </gml:TimePeriod>
         </gmd:extent>
      </gmd:EX_TemporalExtent>
    </gmd:temporalElement>
 </gmd:EX_Extent
```

**Comment by tomkralidis** [comment]
Thamks @gaubert; I've made some minor editorial updates in c45d2ce4e8f49b85c75daa2700f4fbb7058fa2c9.

RE: Bulletins: I put a first pass forth in https://github.com/wmo-im/wcmp/compare/KPI-G .  Questions:
- should bulletin rules have its own KPI (G) or be folded into E?

Regarding:
>> A begin, end time is needed and a description can be added. The begin/end time is mandatory and description is optional.
What should begin or end contain because only 24 hr is retained in the cache. It cannot be a relative duration (begin and end have to contain real dates).

Does this mean we are unable to use `inderterminatePosition="now"` in WCMP Temporal contructs?

**Comment by gaubert** [comment]
@tomkralidis sorry for missing the meeting last Monday. We had a problem because of the recent launch and just manage to go back to a normal work flow. I will attend next Monday.

In my opinion I would put KPI G into E with a special case for bulletins. 

What do you think ?

And then we still will have to use now yes as it is mandatory but we can put a description if that helps. Apparently as @efucile was mentioning that could be the case so. Thoughts ?

**Comment by tomkralidis** [comment]
@gaubert no problem, I hope everything worked out.  +1 to move KPI G into E.

**Comment by gaubert** [comment]
Hi all, (@tomkralidis, @amilan17, @martaguti , @josusky and all) I've  added the add ons from the meeting.  It is ready to be reviewed 
https://github.com/wmo-im/wcmp/blob/KPI-E/KPI/E.adoc

**Comment by tomkralidis** [comment]
Thanks @gaubert; comments:
- The Temporal Extent is well formatted (with a begin and an end) -> The Temporal Extent contains both a begin and end
- The begin data time is inferior or equal to the end date time -> The begin date time is less than or equal to the end date time
- The Data Update Frequency is well formatted -> The Data Update Frequency is present
- The Data Update Frequency is present in 'gmd:maintenanceAndUpdateFrequency\` - > The Data Update Frequency is present in `gmd:maintenanceAndUpdateFrequency` (backticks fix)

**Comment by amilan17** [comment]
@gaubert  the total score is now 5.

**Comment by gaubert** [comment]
Hi all ok I have updated the KPI according to the comments. There are now only 4 checks so the score is back to 4.
Please check

**Comment by tomkralidis** [comment]
LGTM @gaubert .  At this point, can you open a Pull Request?  Thanks

**Comment by gaubert** [comment]
@tomkralidis done. Created pull request KPI E

**Comment by gaubert** [comment]
@amilan17 @tomkralidis for the issue regarding the temporal information for the GTS cache and also forecast.

The issue as I understand it from Enrico is as follow (see above in the issue track):
 Some datasets are on going and have a retention time. Because of the way the time information is specified in ISO, this creates some misleading product pages with confusing time information. See here for instance : http://www.bom.gov.au/metadata/catalogue/19115/ANZCW0503900324 with begin = now and end = now.

This is a valid problem for all the GTS data that is kept in the GISC cache so we can try to solve the problem for them first.

We need to describe the retention time of the datasets somewhere (a rolling forecast dataset with only the last 7 days of data available). Users should understand when discovering the GTS cache datasets that you only have 24hrs of data available and this is not the case.

So how do we describe the rolling datasets with the ISO and how should it be rendered in the discovery pages as well ?
(what information the portals have to extract to present it to users ?)

We could provide some guidance to describe the on-going datasets. 
@efucile was suggesting to use the description field in the temporal extent. In addition as suggested by @amilan17 there is probably a place in the ISO to describe the retention info.

Thoughts, suggestions ?

**Comment by tomkralidis** [comment]
@gaubert thanks for the redux.  To recap, we could have the following:

```xml
    <gmd:temporalElement>
       <gmd:EX_TemporalExtent>
          <gmd:extent>
             <gml:description>Last 24hrs available</gml:description>
             <gml:TimePeriod gml:id="te_001">
                 <gml:beginPosition>2000-11-11T11:11:11Z</gml:beginPosition>
                 <gml:endPosition indeterminatePosition="now"/>
             </gml:TimePeriod>
         </gmd:extent>
      </gmd:EX_TemporalExtent>
    </gmd:temporalElement>
```

On the other hand, the purpose of the discovery metadata is to describe a resource with an ongoing extent, but in principle with a fixed start time.  Say a NMHS has been producing SYNOPs since `2000-11-11T11:11:11Z`, the fact they are distributed with a retention time of, say, 24 hours, is orthogonal to the lifecycle of the actual resource.  And the decision to keep 24 hours, or 1 month, or 6 months, etc. may be specific to the distribution capabilities/policy/retention.  That still doesn't change the fact that the SYNOPs have been around since `2000-11-11T11:11:11Z`.

To summarize, aren't describing the resource's temporal extent and its distribution characteristics regarding retention different things?  In this, sense, we could update the discovery metadata's distribution section with an appropriate description.  Example:

```xml
<!-- in gmd:identificationInfo -->
    <gmd:temporalElement>
       <gmd:EX_TemporalExtent>
          <gmd:extent>
             <gml:TimePeriod gml:id="te_001">
                 <gml:beginPosition>2000-11-11T11:11:11Z</gml:beginPosition>
                 <gml:endPosition indeterminatePosition="now"/>
             </gml:TimePeriod>
         </gmd:extent>
      </gmd:EX_TemporalExtent>
    </gmd:temporalElement>
...
<!-- in gmd:distribution -->
            <gmd:onLine>
              <gmd:CI_OnlineResource>
                <gmd:linkage>
                  <gmd:URL>https://example.org/my-synops/latest</gmd:URL>
                </gmd:linkage>
                <gmd:protocol>
                  <gco:CharacterString>WWW:LINK</gco:CharacterString>
                </gmd:protocol>
                <gmd:name>
                  <gco:CharacterString>SYNOP real-time distribution</gco:CharacterString>
                </gmd:name>
                <gmd:description>
                  <gco:CharacterString>Real-time distribution.  Latest 24 hours are provided.</gco:CharacterString>
                </gmd:description>
              </gmd:CI_OnlineResource>
            </gmd:onLine>
```

Either of the options above should provide the ability for users to be aware of the retention.  The question here is which is more applicable/appropriate.

cc @efucile @amilan17 @martaguti

**Comment by gaubert** [comment]
@tomkralidis retention time and the time coverage period are two different things for sure and we could describe the retention time in the distributionInfo gmd:distribution, that's fine.

Still somebody looking for data from 2000-11-11 will find the synop collection but there will be no data available for that time from the service end-point described by the collection and that will be misleading for users. 

It is not possible to describe in the temporal extent the relative time period (last 24hrs) so that it is a limitation we have to accept.

**Comment by tomkralidis** [comment]
thanks @gaubert.  I suppose another option would be for the metadata provider to continuously update their metadata (and for GISCs/etc. to continuously harvest), but this is impractical and a high barrier to entry.

So we live with this reality and then need to choose where we express the retention time:

- Option 1: in `/gmd:identificationInfo//gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent/gml:description`
- Option 2: in `/gmd:distributionInfo//gmd:onLine//gmd:description`

Thoughts:
- if we go with Option 2, then this implies that distribution info is required. Having said this, if a metadata provider needs to articulate retention time, aren't they making the data available anyway via `/gmd:distributionInfo//gmd:onLine`?

**Comment by martaguti** [comment]
@gaubert @tomkralidis 
retention cache locations are not necessarily known to be able to reference them at /gmd:distributionInfo//gmd:onLine.
e.g as a DCPC publisher I have no idea what are the GISCS doing to implement the 24h cache.  
@josusky @jsieland  is this implemented in the GISCS  and do they publish cache location ?

**Comment by tomkralidis** [comment]
Thanks @martaguti.  In this case, then we go with Option 1.

**Comment by jsieland** [comment]
> retention cache locations are not necessarily known to be able to reference them at /gmd:distributionInfo//gmd:onLine.
> e.g as a DCPC publisher I have no idea what are the GISCS doing to implement the 24h cache.
> @josusky @jsieland is this implemented in the GISCS and do they publish cache location ?

@martaguti
Currently, the data from the 24h cache is available in our WIS portal via the "product" link which is displayed in the search result list. This uses a so-called "productservice" in the background. Authorizations are also checked and displayed by means of a lock icon: closed lock - no access. For external data only link is called. This will change mid-term but there are no more concrete plans at the moment.

**Comment by josusky** [comment]
@martaguti in other words, the GISC do not (automatically) modify metadata records harvested from DCPCs or NCs, so the content of the metadata catalog, at least in its canonical XML representation, is equal on all GISCs. Retrieval from the GISC "cache" is a service that is largely independent on the metadata catalog.

**Comment by gaubert** [comment]
Ok I have checked and BOM in its example above put both beginPosition and endPosition to now. I would say that it is more an implementation or interpretation issue because I don't quite understand what it means ? The temporal extent should be used to define the temporal limits/period covered by the content of the dataset (INSPIRE definition which is again quite wide). 

So if we interpret it simply for archive data, it should describe the period covered by the content of the dataset in the archive (from 2000-01-10T10h30:00Z) and for GTS data we can assume the same (we could also discuss it because the data is not available anywhere in its GTS form if I take EUMETSAT for instance, but I digress). 
If we want to describe the retention time, we should put it somewhere else as suggested by Tom in the distributionInfo linked to the service providing access to the data but I would not specify it nor create KPIs to not add artificial complexity. 

So I suggest to submit the temporal KPI as is.

Thoughts ?

**Comment by gaubert** [comment]
For the cache I saw that on the WIS wiki: https://community.wmo.int/activity-areas/wmo-information-system-wis/GISC%20cache

All data marked as Global Exchange have to be on the cache. How is it implemented ? No idea, it seems to be completely different depending on the GISCs and without any link with the metadata as @josusky mentioned (might be wrong here).  I thought you had to add a flag in the metadata in one of the elements but I did not find it.

**Comment by josusky** [comment]
@gaubert The flag that you mention (keyword "GlobalExchange") indicates that the data (instances of the product) shall be in the cache. It is specified in the Manual on WIS (pub 1060), requirements 9.1, 9.2 and 9.3. How the cache is implemented and what is the actual retention period (above the obligatory 24 hours) is implementation specific.
BTW, this requirements are part of the check we do in KPI A.

**Comment by gaubert** [comment]
@tomkralidis I have updated KPI E with the requested examples. Please check. I have created as well the pull request.

**Comment by tomkralidis** [comment]
Thanks @gaubert .  FYI, I merged the PR, and re-opened the original KPI E PR at #79 which includes these changes.
