### ISSUE TITLE
add WMCP document sources to this repository

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#56]
**Summary and Purpose**
Part 1 and 2 of WMCP are available in this repository in [PDF](https://github.com/wmo-im/wmcp/tree/master/metadata).  However, the source/editable documents are not equally available.

**Proposal**
Provide editable/sources (Word documents?) in this repository, optionally/ideally add a GitHub action to automagically create the PDFs.

**Reason**
Storing the editable documents in this repository will provide better opportunity for maintenance.

cc @efucile

**Comment by tomkralidis** [comment]
Additional benefit of the document sources is searchability (for example, I cannot search for `gmx:Anchor` across the existing PDFs).

**Comment by amilan17** [comment]
@tomkralidis  -- I'd also really like to see working management of this content in GitHub too. However, please keep in mind that it's not possible to publish directly from GitHub to PDF, because the official WMO publication processes are managed by another part of the organization. In particular, they expect a word document with the track changes and they will then proceed to translate to other languages and publish the official PDFs. That said, I still think it's worth moving this content to GitHub and exploring best approaches. We'd also like to do this for other manuals as well and I think it's worth breaking ground here.

**Comment by tomkralidis** [comment]
Thanks @amilan17.  I'd like to manage the document in GitHub; let's start with the Word doc itself and then test with AsciiDoc, Markdown, pandoc and so on to help evaluate options.

**Comment by amilan17** [comment]
I sent a request to the library and publications group for copies of the WIS manual and guide in word doc format.

**Comment by tomkralidis** [comment]
Update: editable documents will be put in `wis-guides` or `wis-manuals` (or `wis-docs`?) (by @amilan17) with the purpose of feeding future versions of the WMO Core Metadata Profile specification.

**Comment by tomkralidis** [comment]
*.docx files added to https://github.com/wmo-im/wcmp/tree/master/specification (thanks @amilan17).
