### ISSUE TITLE
update Part 5 of the WIS Guide

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#92]
**Summary and Purpose**
Update Part V of the WIS Guide with an editorial review.

**Proposal**

Update the Guide to WIS, Part 5: Guidance for Creating WMO Core Metadata Profile in Version 1.3 with an editorial review in AsciiDoc format.

**Reason**
The Guide to the WMO Information System (colloquially called the "WIS Guide"), ISBN-1061, Part 5 has outdated links and deserves a once over.  This is also an opportunity to create this part of the documentation in a lower barrier format such as AsciiDoc.

cc @wmo-im/tt-wismd

**Comment by tomkralidis** [comment]
First pass implemented in https://github.com/wmo-im/wcmp/tree/issue-92-guide

**Comment by tomkralidis** [comment]
FYI when linkchecking, here's a dump of bad links:

[✖] http://www.ngdc.noaa.gov/docucomp/recordServices
[✖] https://www.ngdc.noaa.gov/docucomp/validationServicesWmo
[✖] http://wis.wmo.int/MD-Validate
[✖] https://www.ngdc.noaa.gov/docucomp/recordServices
[✖] https://wis.wmo.int/WIS-Manual
[✖] http://wis.wmo.int/MD-Examples
[✖] http://wis.wmo.int/MD_Index
[✖] https://community.wmo.int/governance/commission-membership/commission-observation-infrastructures-and-information-systems-infcom/commission-infrastructure-officers/infcom-management-group/standing-committee-information-management-and-technology-sc-imt
[✖] http://wis.wmo.int/MD-Templates
[✖] http://wis.wmo.int/MD_Index
[✖] http://wis.wmo.int/WIS-Manual
[✖] https://wis.wmo.int/MD-Examples

Note that in addition to fixing these, we should also inspect any other links to ensure they are relvant/current, and are not better served by updated links elsewhere.

**Comment by tomkralidis** [comment]
Per our meeting on [2021-05-07](https://github.com/wmo-im/wcmp/wiki/Meeting-2021-05-07#actions), @amilan17 to clarify workflow with WMO publication on updating Part V.

**Comment by amilan17** [comment]
*   no replacement at NOAA, NCEI requires NOAA email to login, but I sent an email to verify. 
    *   [http://www.ngdc.noaa.gov/docucomp/recordServices](http://www.ngdc.noaa.gov/docucomp/recordServices)
    *   [https://www.ngdc.noaa.gov/docucomp/validationServicesWmo](https://www.ngdc.noaa.gov/docucomp/validationServicesWmo)
*   I can't find exact copies of the following pages, but this is a static copy from the old wis wiki that may contain the previous content: [https://old.wmo.int/wiswiki/tiki-index.php%3Fpage=WmoCoreMetadata](https://old.wmo.int/wiswiki/tiki-index.php%3Fpage=WmoCoreMetadata)
    *   [http://wis.wmo.int/MD-Validate](http://wis.wmo.int/MD-Validate)
    *   [https://wis.wmo.int/WIS-Manual](https://wis.wmo.int/WIS-Manual)
    *   [http://wis.wmo.int/MD-Examples](http://wis.wmo.int/MD-Examples)
    *   [http://wis.wmo.int/MD_Index](http://wis.wmo.int/MD_Index)
    *   [http://wis.wmo.int/MD-Templates](http://wis.wmo.int/MD-Templates)
    *   [http://wis.wmo.int/MD_Index](http://wis.wmo.int/MD_Index)
*   correct URL: https://community.wmo.int/group/10510
    *   [https://community.wmo.int/governance/commission-membership/commission-observation-infrastructures-and-information-systems-infcom/commission-infrastructure-officers/infcom-management-group/standing-committee-information-management-and-technology-sc-imt](https://community.wmo.int/governance/commission-membership/commission-observation-infrastructures-and-information-systems-infcom/commission-infrastructure-officers/infcom-management-group/standing-committee-information-management-and-technology-sc-imt)

**Comment by tomkralidis** [comment]
2021-05-21: as discussed at today's TT-WISMD, we agree that the initial work in #104 will act as the bootstrap on which we can improve and update incrementally via AsciiDoc.

Next step is for @jsieland to review and provide update.

**Comment by tomkralidis** [comment]
To confirm, #104 has been merged and now in master branch: https://github.com/wmo-im/wcmp/tree/master/docs/guide

**Comment by amilan17** [comment]
@jsieland - This is the homepage for WCMP on the community site. It can be used to replace some of the broken links as needed. 

https://community.wmo.int/activity-areas/wis/wcmp

**Comment by jsieland** [comment]
@wmo-im/tt-wismd

I did some pull requests for the update of the WIS guide part 5 and requested review from some of you. Most of the changes are minor and/or for better readability. I assume many of those were caused by formatting being lost during conversion to asciidoc. For section 002 - WIS Product Categories I do not have editorial changes so I did not create a PR for that.

Most changes are done for section 006 and 007 - these definitely need further proof reading and presumely need the most attention! 

Also I'm not sure if I got all links fixed correctly - because some of them do not work I could not compare. So please check those, too!

Notes: 
- in the WIS guide each part is numbered and sometimes there are references to specific parts. The asciidoc does not have those numbers! For starters I kept those references but this is something we might think about how to align/handle that
- Longterm I think it would best not only to add a seperate section for the KPI but also to include the related KPI in the applicable table in section 007 (food for thought)

Thanks in advance everybody!

**Comment by tomkralidis** [comment]
2021-06-04 TT-WISMD: @amilan17 would prefer a single branch of all changes to help ease comparison as part of the WMO publication process.

As discussed/agreed, I have:
- reverted the last 3 commits by @jsieland 
- created a new branch https://github.com/wmo-im/wcmp/tree/issue-92-guide
- re-introduced the 3 reverted commits as well as the 6 pull requests by @jsieland into issue-92-guide branch (@jsieland thanks so much for having each of your PRs being a single commit, which made this easy to port)
- opened a PR at https://github.com/wmo-im/wcmp/pull/11.  Note the '[WIP]'.  We can remove once ready for final review.

@jsieland please review https://github.com/wmo-im/wcmp/tree/issue-92-guide to ensure I have not missed any of your updates.  Once you approve, I will delete the 6 branches/pull requests, and then we continue on the consolidated branch `issue-92-guide`.

**Comment by jsieland** [comment]
> @jsieland please review https://github.com/wmo-im/wcmp/tree/issue-92-guide to ensure I have not missed any of your updates. Once you approve, I will delete the 6 branches/pull requests, and then we continue on the consolidated branch `issue-92-guide`.

Thanks @tomkralidis, looks good to me. As discussed I will mention @amilan17 for specific link checks in the consolidated branch.

**Comment by tomkralidis** [comment]
Thanks @jsieland .  Branches cleaned up.  At this point our working branch is https://github.com/wmo-im/wcmp/tree/issue-92-guide

**Comment by amilan17** [comment]
There are many URLs in the XML examples (in the guide), but they are mixed with content in gco:CharacterStrings elements. I think this is a poor practice that we should not advertise it and I'd like to discuss the options. 

1.  do nothing (focus on developing WIS2 stds instead)
2.  delete and don't replace 
3.  replace with xlinks (this is not a new approach, but it's never been included in WCMP and I don't know if GISCs will be able to parse an xpath with xlinks)

examples from the Guide

```
<gmd:geographicIdentifier>
	<gmd:MD_Identifier>
		<gmd:code>
			<gco:CharacterString>
			   South Australia (SA)
			    (http://find.ga.gov.au/FIND/profileinfo/anzlic-allgens.xml#SA)
		    </gco:CharacterString>
		</gmd:code>
	</gmd:MD_Identifier>
</gmd:geographicIdentifier>
```

```
<gmd:title>
	<gco:CharacterString>
		ANZLIC Geographic Extent Name Register
		(http://find.ga.gov.au/FIND/profileinfo/anzlic-allgens.xml)
	</gco:CharacterString>
</gmd:title>
```

```
<gmd:keyword>
	<gco:CharacterString>
          0-20000-0-94287; CAIRNS AERO [http://data.wmo.int/wigosid=0-20000-0-94287]
    </gco:CharacterString>
</gmd:keyword>
```

xlink example

```
<gmd:keyword>
	<gmx:Anchor xlink:href="http://data.wmo.int/wigosid=0-20000-0-94287">CAIRNS AERO</gmx:Anchor>
</gmd:keyword>
```

**Comment by amilan17** [comment]
@wmo-im/tt-wismd - I'd like to get your thoughts on removing the links to the two documents below, as currently referenced in the Guide. They were extracted from the Manual on WIS  (probably in 2014) and have not been updated, but the WIS manual has been republished since then. I don't think Appendix C has changed, but maintaining this practice introduces future asynchronies and more work to manage "non-official" documentation. I recommend replacing this text with information about how to find these sections in the WIS Manual published at the WMO Library. 

_WCMP documentation:_

_Part 1 - Conformance Requirements provides the basic definition of the Core Profile :_ [_http://wis.wmo.int/WCMPpart1_](http://wis.wmo.int/WCMPpart1)_;_

_Part 2 - Abstract Test Suite, Data Dictionary and Code Lists describes the constraints on how metadata may be written and defines the definitions of terms used within the metadata :_ [_http://wis.wmo.int/WCMPPart2;_](http://wis.wmo.int/WCMPPart2;)

**Comment by tomkralidis** [comment]
+1 @amilan17 agree with your recommendation.

**Comment by josusky** [comment]
> @wmo-im/tt-wismd 
> 
> There are many URLs in the XML examples (in the guide), but they are mixed with content in gco:CharacterStrings elements. I think this is a poor practice that we should not advertise it and I'd like to discuss the options. 
> 
> 1. do nothing (focus on developing WIS2 stds instead)
> 2. delete and don't replace
> 3. replace with xlinks (this is not a new approach, but it's never been included in WCMP and I don't know if GISCs will be able to parse an xpath with xlinks)
> 
In the KPIs, we recommend the use of xlinks (gmd:Anchor). But I would prefer option **1** because in case of the option **3** we would need to define new examples, as the current ones are not only ugly but also refer to dead URLs (try "http://find.ga.gov.au/FIND/profileinfo/anzlic-allgens.xml#SA").

**Comment by tomkralidis** [comment]
> @wmo-im/tt-wismd 
> 
> There are many URLs in the XML examples (in the guide), but they are mixed with content in gco:CharacterStrings elements. I think this is a poor practice that we should not advertise it and I'd like to discuss the options. 
> 
> 1. do nothing (focus on developing WIS2 stds instead)
> 2. delete and don't replace
> 3. replace with xlinks (this is not a new approach, but it's never been included in WCMP and I don't know if GISCs will be able to parse an xpath with xlinks)
> 

+1 for option 1.

**Comment by jsieland** [comment]
@amilan17 
As discussed at our last [meeting (2021-06-22)](https://github.com/wmo-im/wcmp/wiki/Meeting-2021-06-22) here is the summary of my changes (first review) for every section:

* **000 - Introduction**
. minor formatting for better readability
. link check
* **001 - WIS Discovery Metadata**
. minor formatting for better readability (bullet points)
* **002 - WIS Product Categories**
. no changes
* **003 - Compliance with additional metadata standards**
. removed "additional" from headline for clarification
. minor formatting for clarification
* **004 - WCMP Validaton Tools**
. added a sentence for clarification for validating additional standards
. link check
* **005 - Principles of metadata management in the WIS**
. minor formatting for better readability (subheading)
. link check
* **006 - Generating metadata records compliant with the WCMP**
. added template-based principle for clarification in section 007 
. removed all file-related parts because source is not clear: 5.7.7 + 5.7.8 (partly) + 5.7.11 + 5.7.13 
. more generic wording for removed file-related parts
* **007 - Necessary information to create WCMP**
. added "Category" in the first bullet list for consistency with tables
. table formatting: remove empty first row + necessity as first row + listing if more than one template value 
. formatting XML-elements  for better readability and clarification
. added captions for examples if applicable
. fix formatting if necessary (subheadings, enumerations, etc.)
* **008 - Technical Document**
. link check
* **009 - Annex**
. minor formatting for better readability

**Summary**
Mostly minor clarifications and formatting changes for better readability. Major changes in section 006 + 007.
